### ISSUE TITLE
KeyError: "missing key 'use_paragraphs' from config file"

### ISSUE THREAD

**Issue by ozanarkancan** [clic-lab/ciff#6]
Hi,

Thank you for sharing this code base. I have tried to run the stop baseline for the house environment but got the key error. Here is the full output:
```python
{
  "vocab_size": 1034,
  "vocab_file": "data/house/vocab.txt",
  "num_actions": 7,
  "image_height": 256,
  "image_width": 400,
  "stepPos": 0.1,
  "stepAngle": 90,
  "enableCollision": true,
  "hold": true,
  "doorCollisionSlack": 0.45,
  "plannerMode": false,
  "action_names": [
    "forward",
    "back",
    "slideleft",
    "slideright",
    "lookleft",
    "lookright",
    "stop"
  ],
  "stop_action": "stop",
  "use_pointer_model": false,
  "do_action_prediction": false,
  "do_temporal_autoencoding": false,
  "do_object_detection": false,
  "do_symbolic_language_prediction": false,
  "do_goal_prediction": false
}
Traceback (most recent call last):
  File "src/experiments_house/test_stop.py", line 129, in <module>
    main()
  File "src/experiments_house/test_stop.py", line 45, in main
    setup_validator.validate(config, constants)
  File "/scratch/users/ocan13/ciff/src/setup_agreement/abstract_validate_setup.py", line 20, in validate
    AbstractSetupValidator.validate_core(config, constants)
  File "/scratch/users/ocan13/ciff/src/setup_agreement/abstract_validate_setup.py", line 28, in validate_core
    % config_key)
KeyError: "missing key 'use_paragraphs' from config file"
```

**Comment by dkmisra** [comment]
Hi @ozanarkancan. Thanks for pointing out the bug. We are still working on making the code standardized and so things are in a flux. The error you mentioned is very easy to fix and I'll fix it very soon. Please check out the repository next week and in the mean time feel free to suggest more improvements or features.

**Comment by stefanpantic** [comment]
Any word on this?

**Comment by dkmisra** [comment]
I added the "use_paragraphs" flag. This flag denotes if the code will use the paragraph data or sentence level data. Currently it it set to sentence and that's also the only functionality we currently support for the CHAI corpus. 

You can see it here: 

http://clic.nlp.cornell.edu/resources/Misra-EMNLP-2018/Dataset_and_Simulators/data/house/config.json
